# Generated by Django 5.2.7 on 2025-10-26 18:53

import tasks_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_comment_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tasks_app.utils.task_image_path),
        ),
    ]
