# Generated by Django 5.2.7 on 2025-10-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0005_remove_task_image_taskimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
