# Generated by Django 5.2.7 on 2025-10-31 20:41

import tasks_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=tasks_app.utils.avatar_upload_path),
        ),
    ]
